name: example
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  paginate_firestore:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
