name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.0.3+1
homepage: https://github.com/surveshoeb/paginate_firestore
issue_tracker: https://github.com/surveshoeb/paginate_firestore/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.17.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
